package pilisaru.util;

public enum Rout {
    LOGOUT , LOGIN , COMPOST, ADD_EMP, GET_EMP, UPDATE_EMP, HOME, INVENTORY_MAIN, PILE, GET_SALARY, UPDATE_SALARY,ADD_VEH,GET_VEH,UPD_VEH,ADD_Sale,GET_Sale,UPD_HEALTH,GET_HEALTH
}
