package pilisaru.util;

public enum Rout {
    LOGOUT , LOGIN , COMPOST, ADD_EMP, GET_EMP, UPDATE_EMP, HOME, INVENTORY_MAIN, PILE, GET_SALARY, UPDATE_SALARY, ADD_VEH,
    GET_VEH, UPD_VEH, ADD_Sale, GET_Sale, UPD_HEALTH, GET_HEALTH, INVENTORY_COM_UP, INVENTORY_COM_GET,
    INVENTORY_ADD_EMP, INVENTORY_DELETE_EMP, INVENTORY_UP_EMP, INVENTORY_CHEM_ADD, INVENTORY_CHEM_DELETE, INVENTORY_CHEM_UPDATE,
    INVENTORY_SITE_VEHICLE_ADD, INVENTORY_SITE_VEHICLE_DELETE, INVENTORY_SITE_VEHICLE_UP,
    INVENTORY_MACHINE_UP, INVENTORY_MACHINE_DELETE, INVENTORY_MACHINE_ADD
}
